"""Render generated docs: the topology (a flat repo list) and the persona roster."""

from __future__ import annotations

from . import config

BANNER = (
    "<!-- GENERATED by `edm docs` from inventory/repos.json — "
    "do not edit by hand. -->"
)

#: Markers delimiting the generated roster block inside the hand-written README.
PERSONAS_BEGIN = "<!-- BEGIN personas — GENERATED by `edm docs`; do not edit by hand. -->"
PERSONAS_END = "<!-- END personas -->"


def _cell(text: str) -> str:
    return (text or "").replace("|", "\\|").replace("\n", " ").strip()


def topology_md(doc: dict) -> str:
    repos = sorted(doc.get("repos", []), key=lambda r: r["name"])
    out = [
        BANNER,
        "",
        "# EasyDMARC Repository Topology",
        "",
        f"**{len(repos)} repos** in the `{config.GROUP}` GitLab group. "
        "Refresh with `edm discover`.",
        "",
        "> Repos are cloned on demand into `workspaces/<workspace>/<name>/` "
        "(gitignored). This list is complete even when nothing is cloned.",
        "",
        "| Repo | Kind | Stack | Branch | Description |",
        "| --- | --- | --- | --- | --- |",
    ]
    for r in repos:
        out.append(
            f"| `{r['name']}` | {r['kind']} | {r['stack']} | "
            f"`{r['default_branch']}` | {_cell(r.get('description'))} |"
        )
    out.append("")
    return "\n".join(out)


def _bar(n: int, peak: int, width: int = 12) -> str:
    """Unicode bar, rendered from committed counts so every engineer sees the same one."""
    if peak <= 0:
        return "░" * width
    filled = max(1, round(width * n / peak)) if n else 0
    return "█" * filled + "░" * (width - filled)


def personas_md() -> str:
    """The generated roster block for README.md — who exists, and who is actually *used*.

    Every column is sourced from **committed** state (charters, memory files, the dispatch
    tally), never from local machine state: vault health is deliberately excluded because
    vaults are gitignored and per-engineer, so putting it here would churn the README and
    conflict between checkouts.
    """
    from . import dispatch, persona

    names = sorted(persona.list_personas())
    tally = dispatch.tally()
    gen, total = dispatch.generic_share()
    rows = []
    for n in names:
        meta = (persona.load(n) or {}).get("meta", {})
        rows.append({
            "name": n,
            "disp": tally.get(n, 0),
            "mem": len(persona.memories(n)),
            "tools": (meta.get("tools") or "").strip(),
            "activity": (meta.get("activity") or "").strip(),
        })
    rows.sort(key=lambda r: (-r["disp"], r["name"]))
    peak = max((r["disp"] for r in rows), default=0)

    out = [PERSONAS_BEGIN, "", "## Personas — roster & routing health", ""]
    if not total:
        out += ["_No dispatches recorded yet._ The tally fills as sub-agents are dispatched; "
                "seed it from past sessions with `edm persona dispatch-backfill`.", ""]
    else:
        pct = 100 * gen // total
        out += [
            f"**{total - gen} of {total} dispatches went to a persona**; {gen} went to a "
            f"generic agent (**{pct}%**). A rising generic share means work a persona owns "
            "is being done without it.",
            "",
            "```mermaid",
            "pie showData",
            '    "dispatched to a persona" : ' + str(total - gen),
            '    "dispatched to a generic agent" : ' + str(gen),
            "```",
            "",
        ]
    out += [
        "| Persona | Dispatches | | Memory | Capability |",
        "| --- | ---: | --- | ---: | --- |",
    ]
    flagged = 0
    for r in rows:
        cap = f"`{r['tools']}`" if r["tools"] else (f"_{r['activity']}_" if r["activity"] else "—")
        flag = " ⚑" if r["disp"] == 0 and total else ""
        flagged += bool(flag)
        out.append(f"| `{r['name']}`{flag} | {r['disp']} | `{_bar(r['disp'], peak)}` | "
                   f"{r['mem']} | {cap} |")
    out.append("")
    if flagged:  # only explain the mark when it actually appears above
        out += [
            "⚑ = **never dispatched**: the persona exists and lints green, but nothing has "
            "ever been routed to it. A persona earns its place by carrying a capability a "
            "generic sub-agent can't have — a credential/tool, or a domain narrow enough "
            "to name.",
            "",
        ]
    out += [
        "Regenerate with `make docs` (also refreshed once per session). Detail: "
        "`edm persona stats` · `docs/personas.md`.",
        "",
        PERSONAS_END,
    ]
    return "\n".join(out)


def splice_personas(readme: str) -> str | None:
    """Replace the marked roster block in *readme*. Returns None when the markers are
    absent, so a hand-written README is never appended to by surprise."""
    i = readme.find(PERSONAS_BEGIN)
    j = readme.find(PERSONAS_END)
    if i < 0 or j < 0 or j < i:
        return None
    return readme[:i] + personas_md() + readme[j + len(PERSONAS_END):]
